name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login != 'tarantool'
    strategy:
      matrix:
        tarantool: ["2.11"]
      fail-fast: false
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v5
      - uses: tarantool/setup-tarantool@v4
        with:
          tarantool-version: ${{ matrix.tarantool }}
      - run: |
         wget -O /tmp/tt.deb https://github.com/tarantool/tt/releases/download/v2.11.0/tt_2.11.0_amd64.deb
         sudo apt install /tmp/tt.deb

      - name: Build module
        run: |
          tt rocks make

      - name: Run linter
        run: |
          tt rocks install luacheck 0.25.0
          .rocks/bin/luacheck .

      - name: Run tests
        run: |
          git clone https://github.com/bjornbytes/graphql-lua
          tt rocks make --chdir graphql-lua
          tt rocks install luatest 1.2.1
          .rocks/bin/luatest -v
