name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login != 'tarantool'
    strategy:
      matrix:
        tarantool: ["2.10"]
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: tarantool/setup-tarantool@v4
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Build module
        run: |
          tarantoolctl rocks make

      - name: Run linter
        run: |
          tarantoolctl rocks install luacheck 0.25.0
          .rocks/bin/luacheck .

      - name: Run tests
        run: |
          git clone https://github.com/bjornbytes/graphql-lua
          sed -i 's/lpeg/lulpeg/g' graphql-lua/graphql-0.0.2-1.rockspec
          sed -i "s/local lpeg = require 'lpeg'/local lpeg = require 'lulpeg'/g" graphql-lua/graphql/parse.lua
          tarantoolctl rocks make --chdir graphql-lua
          tarantoolctl rocks install luatest 1.2.1
          .rocks/bin/luatest -v
